image: Visual Studio 2017

clone_script:
- cmd: echo %appveyor_build_worker_image%
build: off
test: off
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
